services:
  db:
    image: postgres:15
    container_name: textbin-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: textbin-app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
volumes:
  db_data: 