version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: textbin
      POSTGRES_PASSWORD: textbinpass
      POSTGRES_DB: textbin
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://textbin:textbinpass@db:5432/textbin
    depends_on:
      - db
volumes:
  db_data: 